apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30000
      port: 81
      targetPort: 80
  selector:
    app: web